name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run sync script
        run: node sync.js
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}

      - name: Commit and push
        run: |
          git config --global user.name "leetcode-bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "sync leetcode" || echo "No changes"
          git push
